# Generated by Django 4.2.1 on 2023-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales_network', '0002_alter_unit_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Звено', 'verbose_name_plural': 'Звенья'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
