# Generated by Django 4.2.1 on 2023-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales_network', '0003_alter_contact_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='product',
            field=models.ManyToManyField(
                blank=True, null=True, to='sales_network.product'
            ),
        ),
    ]
